/**
 * Tunes — frequency, duration, and shape for every sound role.
 * Each tune is a blueprint; the factory + instrument turn it into audio.
 */

import type { BaseTune, SoundRole } from "./types";

// ── Role → Tune mapping ──

export const ROLE_TUNES: Record<SoundRole, BaseTune> = {
  // ── Interaction (40–90 ms) ──
  "interaction.tap": {
    type: "click",
    duration: 0.008,
    filterFreq: 3800,
    filterQ: 2.5,
    volume: 0.5,
    meta: { decayConstant: 35 },
  },
  "interaction.subtle": {
    type: "click",
    duration: 0.008,
    filterFreq: 3600,
    filterQ: 3.5,
    volume: 0.35,
    meta: { decayConstant: 25 },
  },
  "interaction.toggle": {
    type: "toggle",
    duration: 0.035,
    frequency: 700,
    endFrequency: 480,
    volume: 0.4,
    meta: { noiseGain: 0.2, toneGain: 0.22 },
  },
  "interaction.confirm": {
    type: "click",
    duration: 0.012,
    filterFreq: 5500,
    filterQ: 4,
    volume: 0.6,
    meta: { decayConstant: 55 },
  },

  // ── Overlay (120–300 ms) ──
  "overlay.open": {
    type: "rise",
    duration: 0.2,
    frequency: 320,
    endFrequency: 480,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.12,
    meta: { clickLayer: true },
  },
  "overlay.close": {
    type: "drop",
    duration: 0.2,
    frequency: 480,
    endFrequency: 320,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.12,
    meta: { clickLayer: true },
  },
  "overlay.expand": {
    type: "rise",
    duration: 0.13,
    frequency: 380,
    endFrequency: 500,
    volume: 0.3,
    harmonics: true,
    harmonicRatio: 1.5,
    harmonicVolume: 0.1,
    meta: { clickLayer: true },
  },
  "overlay.collapse": {
    type: "drop",
    duration: 0.13,
    frequency: 500,
    endFrequency: 380,
    volume: 0.3,
    harmonics: true,
    harmonicRatio: 1.5,
    harmonicVolume: 0.1,
    meta: { clickLayer: true },
  },

  // ── Navigation (100–250 ms) ──
  "navigation.forward": {
    type: "sweep",
    duration: 0.16,
    frequency: 280,
    endFrequency: 440,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 4,
    harmonicVolume: 0.12,
  },
  "navigation.backward": {
    type: "sweep",
    duration: 0.16,
    frequency: 440,
    endFrequency: 280,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 4,
    harmonicVolume: 0.12,
  },
  "navigation.tab": {
    type: "pop",
    duration: 0.04,
    frequency: 680,
    endFrequency: 880,
    volume: 0.35,
    attack: 0.002,
    decay: 0.035,
  },
  "navigation.scroll": {
    type: "tick",
    duration: 0.005,
    filterFreq: 5000,
    filterQ: 1.5,
    volume: 0.15,
    meta: { decayConstant: 60 },
  },

  // ── Notification (200–600 ms) ──
  "notification.info": {
    type: "chime",
    duration: 0.22,
    frequency: 587.33,
    volume: 0.3,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.15,
  },
  "notification.success": {
    type: "arpeggio",
    duration: 0.4,
    notes: [523.25, 659.25],
    noteDuration: 0.1,
    noteGap: 0.12,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.1,
    meta: { finalRing: 0.25 },
  },
  "notification.warning": {
    type: "arpeggio",
    duration: 0.4,
    notes: [440, 440],
    noteDuration: 0.1,
    noteGap: 0.12,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.1,
    meta: { finalRing: 0.25, semitoneTension: true },
  },
  "notification.error": {
    type: "arpeggio",
    duration: 0.4,
    notes: [493.88, 349.23],
    noteDuration: 0.1,
    noteGap: 0.12,
    volume: 0.4,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.1,
    meta: { finalRing: 0.25 },
  },

  // ── Hero (800–1800 ms, disabled by default) ──
  "hero.complete": {
    type: "arpeggio",
    duration: 1.1,
    notes: [261.63, 329.63, 392.0, 523.25, 659.25],
    noteDuration: 0.12,
    noteGap: 0.08,
    volume: 0.4,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.15,
    meta: { finalRing: 0.55, shimmerCents: 3 },
  },
  "hero.milestone": {
    type: "arpeggio",
    duration: 0.65,
    notes: [261.63, 329.63, 392.0],
    noteDuration: 0.12,
    noteGap: 0.08,
    volume: 0.35,
    harmonics: true,
    harmonicRatio: 2,
    harmonicVolume: 0.15,
    meta: { finalRing: 0.3, shimmerCents: 3 },
  },
};
