export const siteConfig = {
    title: "FreeTheAi",
    aliases: ["Free The AI", "Free The Ai", "FreeTheAI", "FreeTheAi.xyz"],
    description:
        "FreeTheAi, also searched as Free The AI, is a free OpenAI-compatible AI API gateway with 50+ active models, Discord key signup, daily check-in, chat completions, streaming, tool calling, Anthropic messages, and optional paid slots.",
    site: "https://freetheai.xyz",
    author: {
        name: "FreeTheAi",
        url: "https://freetheai.xyz",
    },
    socials: {
        discord: "https://discord.gg/secrets",
        github: "https://github.com/Free-The-Ai/free-ai",
        api: "https://api.freetheai.xyz",
        donate: "https://buymeacoffee.com/vibheksoni",
    },
    defaults: {
        locale: "en_US",
        twitterCard: "summary_large_image",
        ogImage: "/freetheai-transparent-logo-responsive-same-colors.png",
        keywords: [
            "free the ai",
            "free the ai api",
            "free the ai xyz",
            "free the ai website",
            "free the ai discord",
            "freetheai",
            "free theai",
            "freetheai api",
            "freetheai xyz",
            "freetheai discord",
            "free ai api",
            "free openai api",
            "openai compatible api",
            "free openai compatible api",
            "free llm api",
            "free gpt api",
            "free claude api",
            "free gemini api",
            "free deepseek api",
            "free ai models",
            "free chat completions",
            "free chat completions api",
            "openai api free",
            "openai api alternative",
            "free ai api key",
            "discord ai api",
            "discord api key signup",
            "no billing ai api",
            "free streaming ai api",
            "free tool calling api",
            "free ai api docs",
            "anthropic messages api free",
            "free ai gateway",
            "openai compatible api gateway",
            "free openai compatible api gateway",
            "roleplay ai api",
            "free roleplay api",
            "sillytavern api provider",
            "janitor ai proxy api",
            "chub ai proxy",
            "coding agent api",
            "cline openai compatible api",
            "opencode openai compatible api",
            "roo code api provider",
            "aider openai compatible api",
            "ai model catalog",
            "free ai for developers",
            "free ai for students",
            "agent framework api",
            "live ai model catalog",
            "50 active models api",
            "free api no daily limit",
            "ai api without credit card",
            "free llm access",
            "open model api",
            "free ai inference",
            "paid ai api",
            "paid llm api",
            "premium ai models",
        ],
    },
};
